{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "children": [
          {
            "children": [],
            "cpe_match": [
              {
                "cpe23Uri": "cpe:2.3:a:ibm:datastage:-:*:*:*:*:*:*:*",
                "cpe_name": [],
                "vulnerable": true
              }
            ],
            "operator": "OR"
          },
          {
            "children": [],
            "cpe_match": [
              {
                "cpe23Uri": "cpe:2.3:a:ibm:cloud_pak_for_data:*:*:*:*:*:*:*:*",
                "cpe_name": [],
                "versionEndIncluding": "4.5.2",
                "versionStartIncluding": "4.0.6",
                "vulnerable": false
              }
            ],
            "operator": "OR"
          }
        ],
        "cpe_match": [],
        "operator": "AND"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "psirt@us.ibm.com",
      "ID": "CVE-2022-38714"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "IBM DataStage on Cloud Pak for Data 4.0.6 to 4.5.2 stores sensitive credential information that can be read by a privileged user.  IBM X-Force ID:  235060."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-522"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://exchange.xforce.ibmcloud.com/vulnerabilities/235060",
          "refsource": "",
          "tags": [
            "VDB Entry",
            "Vendor Advisory"
          ],
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/235060"
        },
        {
          "name": "https://exchange.xforce.ibmcloud.com/vulnerabilities/235060",
          "refsource": "",
          "tags": [
            "VDB Entry",
            "Vendor Advisory"
          ],
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/235060"
        },
        {
          "name": "https://www.ibm.com/support/pages/node/6618039",
          "refsource": "",
          "tags": [
            "Vendor Advisory"
          ],
          "url": "https://www.ibm.com/support/pages/node/6618039"
        },
        {
          "name": "https://www.ibm.com/support/pages/node/6618039",
          "refsource": "",
          "tags": [
            "Vendor Advisory"
          ],
          "url": "https://www.ibm.com/support/pages/node/6618039"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV3": {
      "cvssV3": {
        "attackComplexity": "LOW",
        "attackVector": "NETWORK",
        "availabilityImpact": "NONE",
        "baseScore": 4.9,
        "baseSeverity": "MEDIUM",
        "confidentialityImpact": "HIGH",
        "integrityImpact": "NONE",
        "privilegesRequired": "HIGH",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "vectorString": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:N/A:N",
        "version": "3.1"
      },
      "exploitabilityScore": 1.2,
      "impactScore": 3.6
    }
  },
  "lastModifiedDate": "2025-03-18T20:15Z",
  "publishedDate": "2024-02-12T18:15Z"
}