{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cna@vuldb.com",
      "ID": "CVE-2025-2723"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Rejected reason: ** REJECT ** DO NOT USE THIS CANDIDATE NUMBER. ConsultIDs: none. Reason: This candidate was withdrawn by its CNA. Further investigation showed that it was not a security issue. Notes: The code maintainer explains that \"[the] call is invalid [as] the buffer pointed to by \"data\" must have \"len\" valid bytes.\" The documentation was fixed to make that clear."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": []
    }
  },
  "impact": {},
  "lastModifiedDate": "2025-04-22T13:15Z",
  "publishedDate": "2025-03-25T01:15Z"
}