{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "security@wikimedia.org",
      "ID": "CVE-2025-32699"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Vulnerability in Wikimedia Foundation MediaWiki, Wikimedia Foundation Parsoid.This issue affects MediaWiki: before 1.39.12, 1.42.6, 1.43.1; Parsoid: before 0.16.5, 0.19.2, 0.20.2."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://phabricator.wikimedia.org/T387130",
          "refsource": "",
          "tags": [],
          "url": "https://phabricator.wikimedia.org/T387130"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2025-04-10T19:16Z",
  "publishedDate": "2025-04-10T19:16Z"
}