{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "children": [],
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:linuxfoundation:pytorch:2.6.0:-:*:*:*:python:*:*",
            "cpe_name": [],
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cna@vuldb.com",
      "ID": "CVE-2025-3000"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "A vulnerability classified as critical has been found in PyTorch 2.6.0. This affects the function torch.jit.script. The manipulation leads to memory corruption. It is possible to launch the attack on the local host. The exploit has been disclosed to the public and may be used."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-119"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://github.com/pytorch/pytorch/issues/149623",
          "refsource": "",
          "tags": [
            "Issue Tracking",
            "Vendor Advisory"
          ],
          "url": "https://github.com/pytorch/pytorch/issues/149623"
        },
        {
          "name": "https://github.com/pytorch/pytorch/issues/149623#issue-2935703015",
          "refsource": "",
          "tags": [
            "Issue Tracking",
            "Vendor Advisory"
          ],
          "url": "https://github.com/pytorch/pytorch/issues/149623#issue-2935703015"
        },
        {
          "name": "VDB-302049 | CTI Indicators (IOB, IOC, IOA)",
          "refsource": "",
          "tags": [
            "Permissions Required",
            "VDB Entry"
          ],
          "url": "https://vuldb.com/?ctiid.302049"
        },
        {
          "name": "VDB-302049 | PyTorch torch.jit.script memory corruption",
          "refsource": "",
          "tags": [
            "Third Party Advisory",
            "VDB Entry"
          ],
          "url": "https://vuldb.com/?id.302049"
        },
        {
          "name": "Submit #524197 | pytorch pytorch (torch.jit.script) torch 2.6.0 Segmentation Fault",
          "refsource": "",
          "tags": [
            "Third Party Advisory",
            "VDB Entry"
          ],
          "url": "https://vuldb.com/?submit.524197"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV3": {
      "cvssV3": {
        "attackComplexity": "LOW",
        "attackVector": "LOCAL",
        "availabilityImpact": "LOW",
        "baseScore": 5.3,
        "baseSeverity": "MEDIUM",
        "confidentialityImpact": "LOW",
        "integrityImpact": "LOW",
        "privilegesRequired": "LOW",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "vectorString": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L",
        "version": "3.1"
      },
      "exploitabilityScore": 1.8,
      "impactScore": 3.4
    }
  },
  "lastModifiedDate": "2025-05-29T15:53Z",
  "publishedDate": "2025-03-31T15:15Z"
}