{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "children": [],
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:d3tn:ud3tn:0.13.0:*:*:*:*:*:*:*",
            "cpe_name": [],
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:d3tn:ud3tn:0.14.1:*:*:*:*:*:*:*",
            "cpe_name": [],
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:d3tn:ud3tn:0.14.2:*:*:*:*:*:*:*",
            "cpe_name": [],
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@gitlab.com",
      "ID": "CVE-2024-12107"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Double-Free Vulnerability in uD3TN BPv7 Caused by Malformed Endpoint Identifier allows remote attacker to reliably cause DoS"
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "GitLab Issue #233",
          "refsource": "",
          "tags": [
            "Exploit",
            "Issue Tracking"
          ],
          "url": "https://gitlab.com/d3tn/ud3tn/-/issues/233"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2025-08-05T17:42Z",
  "publishedDate": "2024-12-04T11:15Z"
}