{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "children": [],
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:gitlab:gitlab:*:*:*:*:community:*:*:*",
            "cpe_name": [],
            "versionEndExcluding": "17.11.4",
            "versionStartIncluding": "17.11.0",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:gitlab:gitlab:*:*:*:*:community:*:*:*",
            "cpe_name": [],
            "versionEndExcluding": "18.0.2",
            "versionStartIncluding": "18.0.0",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:gitlab:gitlab:*:*:*:*:enterprise:*:*:*",
            "cpe_name": [],
            "versionEndExcluding": "17.11.4",
            "versionStartIncluding": "17.11.0",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:gitlab:gitlab:*:*:*:*:enterprise:*:*:*",
            "cpe_name": [],
            "versionEndExcluding": "18.0.2",
            "versionStartIncluding": "18.0.0",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:gitlab:gitlab:*:*:*:*:community:*:*:*",
            "cpe_name": [],
            "versionEndExcluding": "17.10.8",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:gitlab:gitlab:*:*:*:*:enterprise:*:*:*",
            "cpe_name": [],
            "versionEndExcluding": "17.10.8",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@gitlab.com",
      "ID": "CVE-2024-9512"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "An issue has been discovered in GitLab EE affecting all versions prior to 17.10.8, 17.11 prior to 17.11.4, and 18.0 prior to 18.0.2. It may have been possible for private repository to be cloned in case of race condition when a secondary node is out of sync."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-367"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "GitLab Issue #497748",
          "refsource": "",
          "tags": [
            "Broken Link"
          ],
          "url": "https://gitlab.com/gitlab-org/gitlab/-/issues/497748"
        },
        {
          "name": "HackerOne Bug Bounty Report #2683469",
          "refsource": "",
          "tags": [
            "Permissions Required"
          ],
          "url": "https://hackerone.com/reports/2683469"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV3": {
      "cvssV3": {
        "attackComplexity": "HIGH",
        "attackVector": "NETWORK",
        "availabilityImpact": "NONE",
        "baseScore": 5.9,
        "baseSeverity": "MEDIUM",
        "confidentialityImpact": "HIGH",
        "integrityImpact": "NONE",
        "privilegesRequired": "NONE",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "vectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N",
        "version": "3.1"
      },
      "exploitabilityScore": 2.2,
      "impactScore": 3.6
    }
  },
  "lastModifiedDate": "2025-08-08T18:22Z",
  "publishedDate": "2025-06-12T14:15Z"
}