{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cna@mongodb.com",
      "ID": "CVE-2024-5629"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "An out-of-bounds read in the 'bson' module of PyMongo 4.6.2 or earlier allows deserialization of malformed BSON provided by a Server to raise an exception which may contain arbitrary application memory."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://jira.mongodb.org/browse/PYTHON-4305",
          "refsource": "",
          "tags": [],
          "url": "https://jira.mongodb.org/browse/PYTHON-4305"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2024-06-05T15:15Z",
  "publishedDate": "2024-06-05T15:15Z"
}