{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "children": [],
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:ibm:app_connect_enterprise:*:*:*:*:*:*:*:*",
            "cpe_name": [],
            "versionEndExcluding": "11.0.0.26",
            "versionStartIncluding": "11.0.0.1",
            "vulnerable": true
          },
          {
            "cpe23Uri": "cpe:2.3:a:ibm:app_connect_enterprise:*:*:*:*:*:*:*:*",
            "cpe_name": [],
            "versionEndExcluding": "12.0.12.1",
            "versionStartIncluding": "12.0.1.0",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "psirt@us.ibm.com",
      "ID": "CVE-2024-28760"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "IBM App Connect Enterprise 11.0.0.1 through 11.0.0.25 and 12.0.1.0 through 12.0.12.0 dashboard is vulnerable to a denial of service due to improper restrictions of resource allocation.  IBM X-Force ID:  285244."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-770"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://exchange.xforce.ibmcloud.com/vulnerabilities/285244",
          "refsource": "",
          "tags": [
            "VDB Entry"
          ],
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/285244"
        },
        {
          "name": "https://exchange.xforce.ibmcloud.com/vulnerabilities/285244",
          "refsource": "",
          "tags": [
            "VDB Entry"
          ],
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/285244"
        },
        {
          "name": "https://www.ibm.com/support/pages/node/7150845",
          "refsource": "",
          "tags": [
            "Patch",
            "Vendor Advisory"
          ],
          "url": "https://www.ibm.com/support/pages/node/7150845"
        },
        {
          "name": "https://www.ibm.com/support/pages/node/7150845",
          "refsource": "",
          "tags": [
            "Patch",
            "Vendor Advisory"
          ],
          "url": "https://www.ibm.com/support/pages/node/7150845"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV3": {
      "cvssV3": {
        "attackComplexity": "LOW",
        "attackVector": "NETWORK",
        "availabilityImpact": "LOW",
        "baseScore": 4.3,
        "baseSeverity": "MEDIUM",
        "confidentialityImpact": "NONE",
        "integrityImpact": "NONE",
        "privilegesRequired": "LOW",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:L",
        "version": "3.1"
      },
      "exploitabilityScore": 2.8,
      "impactScore": 1.4
    }
  },
  "lastModifiedDate": "2025-01-07T21:02Z",
  "publishedDate": "2024-05-14T15:14Z"
}