{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2024-48063"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "In PyTorch \u003c=2.4.1, the RemoteModule has Deserialization RCE. NOTE: this is disputed by multiple parties because this is intended behavior in PyTorch distributed computing."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://rumbling-slice-eb0.notion.site/Distributed-RPC-Framework-RemoteModule-has-Deserialization-RCE-in-pytorch-pytorch-111e3cda9e8c8021a7d3cbc61ee1a20c",
          "refsource": "",
          "tags": [],
          "url": "https://rumbling-slice-eb0.notion.site/Distributed-RPC-Framework-RemoteModule-has-Deserialization-RCE-in-pytorch-pytorch-111e3cda9e8c8021a7d3cbc61ee1a20c"
        },
        {
          "name": "https://gist.github.com/hexian2001/c046c066895a963ecc0a2cf9e1180065",
          "refsource": "",
          "tags": [],
          "url": "https://gist.github.com/hexian2001/c046c066895a963ecc0a2cf9e1180065"
        },
        {
          "name": "https://github.com/pytorch/pytorch/issues/129228",
          "refsource": "",
          "tags": [],
          "url": "https://github.com/pytorch/pytorch/issues/129228"
        },
        {
          "name": "https://github.com/pytorch/pytorch/security/policy#using-distributed-features",
          "refsource": "",
          "tags": [],
          "url": "https://github.com/pytorch/pytorch/security/policy#using-distributed-features"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2024-11-01T13:15Z",
  "publishedDate": "2024-10-29T21:15Z"
}