{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "children": [],
        "cpe_match": [
          {
            "cpe23Uri": "cpe:2.3:a:radare:radare2:*:*:*:*:*:*:*:*",
            "cpe_name": [],
            "versionEndIncluding": "5.9.4",
            "versionStartIncluding": "5.8.0",
            "vulnerable": true
          }
        ],
        "operator": "OR"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "cve@mitre.org",
      "ID": "CVE-2024-48241"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "An issue in radare2 v5.8.0 through v5.9.4 allows a local attacker to cause a denial of service via the __bf_div function."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://github.com/radareorg/radare2/issues/23317",
          "refsource": "",
          "tags": [
            "Issue Tracking",
            "Vendor Advisory"
          ],
          "url": "https://github.com/radareorg/radare2/issues/23317"
        },
        {
          "name": "https://github.com/radareorg/radare2/pull/23318",
          "refsource": "",
          "tags": [
            "Issue Tracking",
            "Vendor Advisory"
          ],
          "url": "https://github.com/radareorg/radare2/pull/23318"
        },
        {
          "name": "https://github.com/St-Andrews-Bug-Busters/Vuln_info/blob/main/radare2/CVE-2024-48241.md",
          "refsource": "",
          "tags": [
            "Third Party Advisory"
          ],
          "url": "https://github.com/St-Andrews-Bug-Busters/Vuln_info/blob/main/radare2/CVE-2024-48241.md"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2025-06-13T00:24Z",
  "publishedDate": "2024-10-30T18:15Z"
}