{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "secalert@redhat.com",
      "ID": "CVE-2023-38472"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "A vulnerability was found in Avahi. A reachable assertion exists in the avahi_rdata_parse() function."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=2191692",
          "refsource": "MISC",
          "tags": [],
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2191692"
        },
        {
          "name": "https://access.redhat.com/security/cve/CVE-2023-38472",
          "refsource": "MISC",
          "tags": [],
          "url": "https://access.redhat.com/security/cve/CVE-2023-38472"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2023-11-02T18:21Z",
  "publishedDate": "2023-11-02T15:15Z"
}