{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "secalert@redhat.com",
      "ID": "CVE-2023-4010"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "A flaw was found in the USB Host Controller Driver framework in the Linux kernel. The usb_giveback_urb function has a logic loophole in its implementation. Due to the inappropriate judgment condition of the goto statement, the function cannot return under the input of a specific malformed descriptor file, so it falls into an endless loop, resulting in a denial of service."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": []
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://access.redhat.com/security/cve/CVE-2023-4010",
          "refsource": "MISC",
          "tags": [],
          "url": "https://access.redhat.com/security/cve/CVE-2023-4010"
        },
        {
          "name": "https://bugzilla.redhat.com/show_bug.cgi?id=2227726",
          "refsource": "MISC",
          "tags": [],
          "url": "https://bugzilla.redhat.com/show_bug.cgi?id=2227726"
        },
        {
          "name": "https://github.com/wanrenmi/a-usb-kernel-bug",
          "refsource": "MISC",
          "tags": [],
          "url": "https://github.com/wanrenmi/a-usb-kernel-bug"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2023-07-31T17:30Z",
  "publishedDate": "2023-07-31T17:15Z"
}